package {{package-name}};

import org.json.JSONArray;

import android.webkit.WebView;

import com.mahfouz.qortoba.AndroidQortobaClient;

/**
 * Generated code. DO NOT EDIT.
 *
 * This class is generated by Qortoba command line utility.
 */
 public final class {{class-name}}  {

    private final AndroidQortobaClient qortobaClient;

    public {{class-name}} (WebView webView) {
        if (webView == null)
            throw new IllegalArgumentException();
        this.qortobaClient = new AndroidQortobaClient(webView);
    }

    // methods that proxy calls to the JavaScript class

    {{#each methods}}
    public void {{name}}({{#each params}}String {{.}}{{#unless @last}}, {{/unless}}{{/each}}) {
        JSONArray jsonParams = new JSONArray();
        {{#params}}
        jsonParams.push({{.}});
        {{/params}}
        qortobaClient.invoke("{{../class-name}}", "{{name}}", jsonParams);
    } 
    {{/each}}
 }